# Natural Language Processing

## Importing the libraries

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [3]:
dataset = pd.read_csv("C:\datasets\Restaurant_Reviews.tsv", delimiter = '\t', quoting = 3)

## Cleaning the texts

In [4]:
import re
import nltk
# nltk.download('stopwords') #downloads the stopwords
from nltk.corpus import stopwords #imports the downloaded stopwords
from nltk.stem.porter import PorterStemmer #this class helps us remove stem words
corpus = [] #all reviews after being cleaned
for i in range(0, 1000):
    review = re.sub('[^a-zA-Z]', ' ', dataset['Review'][i]) #replaces any element thats not a letter gets replaced by space
    review = review.lower()
    review = review.split()
    ps = PorterStemmer()
    all_stop_words = stopwords.words('english')
    all_stop_words.remove("not")
    review = [ps.stem(word) for word in review if not word in set(all_stop_words)]
    review = ' '.join(review)
    corpus.append(review)
    print(corpus)

['wow love place']
['wow love place', 'crust not good']
['wow love place', 'crust not good', 'not tasti textur nasti']
['wow love place', 'crust not good', 'not tasti textur nasti', 'stop late may bank holiday rick steve recommend love']
['wow love place', 'crust not good', 'not tasti textur nasti', 'stop late may bank holiday rick steve recommend love', 'select menu great price']
['wow love place', 'crust not good', 'not tasti textur nasti', 'stop late may bank holiday rick steve recommend love', 'select menu great price', 'get angri want damn pho']
['wow love place', 'crust not good', 'not tasti textur nasti', 'stop late may bank holiday rick steve recommend love', 'select menu great price', 'get angri want damn pho', 'honeslti tast fresh']
['wow love place', 'crust not good', 'not tasti textur nasti', 'stop late may bank holiday rick steve recommend love', 'select menu great price', 'get angri want damn pho', 'honeslti tast fresh', 'potato like rubber could tell made ahead time kept

['wow love place', 'crust not good', 'not tasti textur nasti', 'stop late may bank holiday rick steve recommend love', 'select menu great price', 'get angri want damn pho', 'honeslti tast fresh', 'potato like rubber could tell made ahead time kept warmer', 'fri great', 'great touch', 'servic prompt', 'would not go back', 'cashier care ever say still end wayyy overpr', 'tri cape cod ravoli chicken cranberri mmmm', 'disgust pretti sure human hair', 'shock sign indic cash', 'highli recommend', 'waitress littl slow servic', 'place not worth time let alon vega', 'not like', 'burritto blah', 'food amaz', 'servic also cute', 'could care less interior beauti', 'perform', 'right red velvet cake ohhh stuff good', 'never brought salad ask', 'hole wall great mexican street taco friendli staff', 'took hour get food tabl restaur food luke warm sever run around like total overwhelm', 'worst salmon sashimi', 'also combo like burger fri beer decent deal', 'like final blow', 'found place accid could not

['wow love place', 'crust not good', 'not tasti textur nasti', 'stop late may bank holiday rick steve recommend love', 'select menu great price', 'get angri want damn pho', 'honeslti tast fresh', 'potato like rubber could tell made ahead time kept warmer', 'fri great', 'great touch', 'servic prompt', 'would not go back', 'cashier care ever say still end wayyy overpr', 'tri cape cod ravoli chicken cranberri mmmm', 'disgust pretti sure human hair', 'shock sign indic cash', 'highli recommend', 'waitress littl slow servic', 'place not worth time let alon vega', 'not like', 'burritto blah', 'food amaz', 'servic also cute', 'could care less interior beauti', 'perform', 'right red velvet cake ohhh stuff good', 'never brought salad ask', 'hole wall great mexican street taco friendli staff', 'took hour get food tabl restaur food luke warm sever run around like total overwhelm', 'worst salmon sashimi', 'also combo like burger fri beer decent deal', 'like final blow', 'found place accid could not

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



## Creating the Bag of Words model

In [6]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 1500)
X = cv.fit_transform(corpus).toarray()
y = dataset.iloc[:, -1].values

## Splitting the dataset into the Training set and Test set

In [58]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

## Training the Naive Bayes model on the Training set

In [71]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

## Predicting the Test set results

In [72]:
y_pred = classifier.predict(X_test)

## Performance Metrics for Naive Bayes

In [73]:
from sklearn.metrics import accuracy_score,precision_score,recall_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("accuracy_score",accuracy_score(y_test,y_pred))
print("Precision score:",precision_score(y_test,y_pred))
print("recall_score:",recall_score(y_test,y_pred))

[[55 42]
 [12 91]]
accuracy_score 0.73
Precision score: 0.6842105263157895
recall_score: 0.883495145631068


## Training the RandomForestClassifier model on the Training set

In [74]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 100, criterion ='entropy',random_state = 0)
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

## Perfromance metrics for RandomForestClassifier

In [75]:
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("accuracy_score",accuracy_score(y_test,y_pred))
print("Precision score:",precision_score(y_test,y_pred))
print("recall score:",recall_score(y_test,y_pred))

[[90  7]
 [39 64]]
accuracy_score 0.77
Precision score: 0.9014084507042254
recall score: 0.6213592233009708


## Training the Support Vector Machine model on the Training set

In [76]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear',random_state = 0,C=1.80)
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

## Performance metrics for SVM

In [77]:
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("accuracy_score",accuracy_score(y_test,y_pred))
print("Precision score:",precision_score(y_test,y_pred))
print("recall_score:",recall_score(y_test,y_pred))

[[78 19]
 [19 84]]
accuracy_score 0.81
Precision score: 0.8155339805825242
recall_score: 0.8155339805825242
